spring.application.name=healthhub

# Database configuration
spring.h2.console.enabled= true
spring.datasource.url=jdbc:h2:mem:healthhubdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=hello

server.port= 8090
